id: P824E4280
initial_creation_type: input
source_metadata:
  Title: Upasampadā jñaptiḥ
  Editor: Dr. K.K.Datta
  Publisher: K.P. Jayaswal Research Institute
  Place of Publication: Patna
  Year: '1961'
  Upasampadā jñaptiḥ:
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:17:05.716186'
last_modified_at: '2022-03-08T17:17:05.716194'
